### ISSUE TITLE
Layer designated indexer using names of indexer class

### ISSUE THREAD

**Issue by houxinli** [tracyhenry/Kyrix#113]
As we discussed a little bit about this in https://github.com/tracyhenry/Kyrix/pull/112#discussion_r319608046. The motivation is that because the number of different indexers is growing and keep using booleans to indicate which indexer is supposed to handle this layer seems not ideal. I'm trying to add a field "indexer" in every layer in the compiler, and using reflection in the back-end to designate the proper indexer, but some details need furthur discussion
@tracyhenry

**Comment by tracyhenry** [comment]
yes agreed.
