### ISSUE TITLE
make backend stateless

### ISSUE THREAD

**Issue by tracyhenry** [tracyhenry/Kyrix#51]
The backend is now stateful because it memorizes the user's history of positions. 

This history should be instead maintained by the client, to make the backend stateless and parallelizable

**Comment by asah** [comment]
y this is a good idea. A hybrid is to make the stateful-backend on a
separate server and then use a simple API to support various kinds of ultra
lightweight hosted servers (e.g. google appengine) instead of requiring
another stateful server to keep running, backed up, scaled up etc etc
