### ISSUE TITLE
config.txt hardcodes database name - inconsistent with docs

### ISSUE THREAD

**Issue by asah** [tracyhenry/Kyrix#62]
Kyrix/compiler/examples/dots/README.md

As defined in `transform.js`, running this app needs a database `dots` with a relation `dots`, whose schema is `create table dots (id int, x int, y int);`.

==> actually, transform.js doesn't define the database name... I'm guessing the dbname is defined in config.txt ?

**Comment by tracyhenry** [comment]
yea you can actually define db name in the transform. The name of the `dots` relation just happens to be the same as the app name.
