### ISSUE TITLE
add more automation to docker scripts

### ISSUE THREAD

**Issue by peterg17** [tracyhenry/Kyrix#70]
TODO: add more detail but basically using environment variables and maybe yml files to specify things like what the application name is, what sql should be run during setup, where we should go in the compiler/examples to run your app's front-end code

**Comment by asah** [comment]
Y agreed!!

(via cellphone, random spelling ahead)

**Comment by tracyhenry** [comment]
I think this can be closed for now. 

With one-command data loading (#57) and dynamic re-loading of apps (#65), almost everything development-related can be done outside docker containers with one command. See [tutorial](https://github.com/tracyhenry/Kyrix/wiki/Tutorial#a-list-of-commonly-used-commands) for more details. 

Reopen if you find anything is not automated enough.
