### ISSUE TITLE
data collection for intersecting rows and fetch times

### ISSUE THREAD

**Issue by peterg17** [tracyhenry/Kyrix#74]
Write code that writes rows that intersect with a query and the time it took to retrieve the results (fetch+send time) to a JSON file. Can then use for data analysis.

**Comment by tracyhenry** [comment]
The way I did data analysis before was to extract the perf numbers from the backend log using some kind of pattern matching. So yes, this can definitely be automated.

It might be more useful to extract it into a spreadsheet file -- you always want to import the numbers into Excel or Google Sheets for plotting and stuff.

**Comment by asah** [comment]
Silly q: have you considered using the database?  SQL is a perfectly good
language for analytics...

FYI Postgres has a builtin query log incl latency, straightforward to
configure it if you want... see
https://www.postgresql.org/docs/current/pgstatstatements.html

**Comment by peterg17** [comment]
Note: this is implemented in BoxRequestHandler.java for dboxes on my branch (indexing-perf-tests) ,but needs to be merged into master. Also I have to figure out how to differentiate between zooming and panning requests in the tile handler to implement stats collection for the tiles as well

**Comment by tracyhenry** [comment]
> Note: this is implemented in BoxRequestHandler.java for dboxes on my branch (indexing-perf-tests) ,but needs to be merged into master. Also I have to figure out how to differentiate between zooming and panning requests in the tile handler to implement stats collection for the tiles as well

ok I added the `completed` label. 
It doesn't seem to me there is existing information in the REST call that tells you if it's panning. But you can maybe use the `isZooming` variable here to do the trick: https://github.com/tracyhenry/Kyrix/blob/918855838124d1c35c7bd9a6fd0eb66e88467531/front-end/js/zoom.js#L253

Just pass it to `refreshDynamicLayers` and then pass it to `renderTiles`

**Comment by tracyhenry** [comment]
> > Note: this is implemented in BoxRequestHandler.java for dboxes on my branch (indexing-perf-tests) ,but needs to be merged into master. Also I have to figure out how to differentiate between zooming and panning requests in the tile handler to implement stats collection for the tiles as well
> 
> ok I added the `completed` label.
> It doesn't seem to me there is existing information in the REST call that tells you if it's panning. But you can maybe use the `isZooming` variable here to do the trick:
> 
> https://github.com/tracyhenry/Kyrix/blob/918855838124d1c35c7bd9a6fd0eb66e88467531/front-end/js/zoom.js#L253
> 
> Just pass it to `refreshDynamicLayers` and then pass it to `renderTiles`


Sorry, that should be a bad idea. 

I think by testing if `gvd.tileRenderData=={}` will do the trick. Since it's reset to `{}` every time there is a jump or page onload: https://github.com/tracyhenry/Kyrix/blob/918855838124d1c35c7bd9a6fd0eb66e88467531/front-end/js/pageOnLoad.js#L66

**Comment by peterg17** [comment]
I'm coding in simple logic to send the fetch time (measured by system clock) and the # of intersecting rows to the stats database table whenever there is a fetch from the front-end. Wenbo suggested we could use an in-memory data structure to store stats and only write to the database occasionally rather than every time a request to the back-end happens. I think that using pg_stats module as adam suggested could be helpful for getting more information about our queries, though I think we should use it in combination with our own stats (because we need to differentiate between pan and zoom interactions)
